# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - group: valueGroup

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 'Default'
    steps:
    - task: BatchScript@1
      inputs:
        filename: ./tests/run_tests.cmd
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerServiceConnection'
        repository: 'cdavenport92/workitemadapter-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.workitem'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerServiceConnection'
        repository: 'cdavenport92/repoadapter-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.repo'