# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - group: valueGroup

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 'Default'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          '$(Build.BuildId)'
    - task: CmdLine@2
      displayName: Alias registry1.io
      inputs:
        script: docker login -u $(dockerUser) -p $(dockerPass) docker.io
    - task: CmdLine@2
      displayName: Alias registry1.io
      inputs:
        script: docker push workitemadapter-app:latest