version: '3'
services:

  workitem:
    build:
      context: .
      dockerfile: Dockerfile.workitem
    image: workitemadapter
    restart: unless-stopped
    ports:
      - 5002:5002
    networks:
      - internalNetwork

  repo:
    build:
      context: .
      dockerfile: Dockerfile.repo
    image: repoadapter
    restart: unless-stopped
    ports:
      - 5001:5001
    networks:
      - internalNetwork

networks:
  internalNetwork:
    driver: bridge